VANTA.BIRDS({
  el: '.firstview',
  mouseControls: true,
  touchControls: true,
  gyroControls: true,
  minHeight: 200,
  minWidth: 200,
  scale: 1,
  scaleMobile: 1,
  backgroundColor: '#110e17',
  color1: '#5918df',
  color2: '#5918df',
  colorMode: 'variance',
  birdSize: 1,
  wingSpan: 20,
  speedLimit: 8,
  separation: 29,
  alignment: 33,
  cohesion: 50,
});
